import = ["/home/deivid/.config/alacritty/themes/themes/nord.toml"]

[font]
size = 9.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
opacity = 1.0

[window.padding]
x = 20
y = 20
